[package]
name = "clifolio"
version = "0.1.0"
authors = ["grigory.k <grisha992@gmail.com>"]
license = "MIT"
edition = "2021"

[dependencies]
ratatui = { version = "0.30.0", default-features = false }
color-eyre = "0.6.5"
ratzilla = "0.2.0"
